export const categories = [
  { name: "All products", icon: "tv" },
  { name: "Electronics", icon: "tv" },
  { name: "Beauty & Cosmetics", icon: "spa" },
  { name: "Computing", icon: "computer" },
  { name: "Gaming", icon: "gamepad" },
  { name: "Kitchen", icon: "spoon" },
  { name: "Fashion", icon: "shirt" },
  { name: "Books", icon: "computer" },
  { name: "Phones & Tablets", icon: "tablet" },
  { name: "Gardening", icon: "trowel" },
  { name: "Sporting", icon: "basketball" },
  { name: "Stationary", icon: "book" },
  { name: "Home & Office", icon: "computer" },
  { name: "Others", icon: "trowel" },
];
