export const categories = [
  {id:1, name: "All products", icon: "tv" },
  {id:2, name: "Home & Office", icon: "house" },
  {id:3, name: "Computing", icon: "computer" },
  {id:4, name: "Tvs & Audio", icon: "tv" },
  {id:5, name: "Gaming", icon: "gamepad" },
  {id:6, name: "Kitchen", icon: "spoon" },
  {id:7,name: "Beauty & Cosmetics", icon: "spa" },
  {id:8, name: "Phones & Tablets", icon: "tablet" },
  {id:9, name: "Fashion", icon: "shirt" },
  {id:10, name: "Appliances", icon: "computer" },
  {id:11, name: "Gardening", icon: "trowel" },
  {id:12, name: "Sporting Goods", icon: "basketball" },
  {id:13, name: "Stationary", icon: "book" },
  {id:14, name: "Drinks", icon: "book" },
  {id:15, name: "Mobile Accessories", icon: "book" },
];
